export const mockCars = [
  {
    make: 'Toyota',
    model: 'Camry',
    year: 2022,
    transmission: 'a',
    drive: 'fwd',
    city_mpg: 28,
    image: '/hero.png',
  },
  {
    make: 'BMW',
    model: 'M4',
    year: 2023,
    transmission: 'a',
    drive: 'rwd',
    city_mpg: 22,
    image: '/hero.png',
  },
  {
    make: 'Audi',
    model: 'A4',
    year: 2021,
    transmission: 'a',
    drive: 'awd',
    city_mpg: 26,
    image: '/hero.png',
  },
  {
    make: 'Tesla',
    model: 'Model 3',
    year: 2023,
    transmission: 'a',
    drive: 'rwd',
    city_mpg: 132,
    image: '/hero.png',
  },
  {
    make: 'Honda',
    model: 'Civic',
    year: 2020,
    transmission: 'm',
    drive: 'fwd',
    city_mpg: 32,
    image: '/hero.png',
  },
  {
    make: 'Ford',
    model: 'Mustang',
    year: 2022,
    transmission: 'm',
    drive: 'rwd',
    city_mpg: 21,
    image: '/hero.png',
  },
];

export const manufacturers = [
  'Acura',
  'Alfa Romeo',
  'Aston Martin',
  'Audi',
  'Bentley',
  'BMW',
  'Buick',
  'Cadillac',
  'Chevrolet',
  'Chrysler',
  'Citroen',
  'Dodge',
  'Ferrari',
  'Fiat',
  'Ford',
  'GMC',
  'Honda',
  'Hyundai',
  'Infiniti',
  'Jaguar',
  'Jeep',
  'Kia',
  'Lamborghini',
  'Land Rover',
  'Lexus',
  'Lincoln',
  'Maserati',
  'Mazda',
  'McLaren',
  'Mercedes-Benz',
  'MINI',
  'Mitsubishi',
  'Nissan',
  'Porsche',
  'Ram',
  'Rolls-Royce',
  'Subaru',
  'Tesla',
  'Toyota',
  'Volkswagen',
  'Volvo',
];

export const yearsOfProduction = [
  { title: 'Year', value: '' },
  { title: '2015', value: '2015' },
  { title: '2016', value: '2016' },
  { title: '2017', value: '2017' },
  { title: '2018', value: '2018' },
  { title: '2019', value: '2019' },
  { title: '2020', value: '2020' },
  { title: '2021', value: '2021' },
  { title: '2022', value: '2022' },
  { title: '2023', value: '2023' },
];

export const fuels = [
  {
    title: 'Fuel',
    value: '',
  },
  {
    title: 'Gas',
    value: 'Gas',
  },
  {
    title: 'Electricity',
    value: 'Electricity',
  },
];

export const footerLinks = [
  {
    title: 'About',
    links: [
      { title: 'How it works', url: '/' },
      { title: 'Featured', url: '/' },
      { title: 'Partnership', url: '/' },
      { title: 'Bussiness Relation', url: '/' },
    ],
  },
  {
    title: 'Company',
    links: [
      { title: 'Events', url: '/' },
      { title: 'Blog', url: '/' },
      { title: 'Podcast', url: '/' },
      { title: 'Invite a friend', url: '/' },
    ],
  },
  {
    title: 'Socials',
    links: [
      { title: 'Discord', url: '/' },
      { title: 'Instagram', url: '/' },
      { title: 'Twitter', url: '/' },
      { title: 'Facebook', url: '/' },
    ],
  },
];
